version: "3"
services:
  client:
    image: client
    build:
      context: client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
  server:
    image: server
    build:
      context: server
      dockerfile: dockerfile
    ports:
      - "5000:5000"